---
# tasks file for lighthouse-role

#- name: Setup Nginx and Git on Debian
#  hosts: lighthouse
#  become: yes
#  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: yes

    - name: Start Nginx service
      systemd:
        name: nginx
        state: started

    - name: Clone VKCOM lighthouse repository
      git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        dest: /var/www/lighthouse

    - name: Copy nginx site configuration
      ansible.builtin.template:
        src: templates/nginx_site_enable.j2
        dest: /etc/nginx/sites-enabled/default
      notify: restart nginx

